### PR TITLE
Miscellaneous Commits

### PR DESCRIPTION
**Pull request by aguentepe**

### CODE REVIEW

**Comment by JM1** [comment]
Thanks for your contributions :grinning: I will have a deeper look as soon as I am back from vacation :wink: Did you try to run your code against the tests? Maybe you have to reenable tests for your code but they are still there.

**Comment by aguentepe** [comment]
Yes, I ran the tests. And they pass except for matrices where m<n.

**Comment by JM1** [comment]
@aguentepe: Sorry for not responding sooner. I did not get any notification about your force-push and somehow all my review comments have been lost?!? Do you have any idea how to make them visible again?

**Comment by aguentepe** [comment]
I found the links to the old commits:
https://github.com/aguentepe/hbrs-mpl/commit/e22654f2d1eeb9f89b759eae72dcd167ecfe3de3
https://github.com/aguentepe/hbrs-mpl/commit/7771d1201faca3cdcbdd468e2c6a84c3c28479b4
https://github.com/aguentepe/hbrs-mpl/commit/c8626ea1287352e799708ac6872af3f36ff06c22
https://github.com/aguentepe/hbrs-mpl/commit/91c24abdefd9838068270d7df8b8a8abcc961a89
https://github.com/aguentepe/hbrs-mpl/commit/cd103bb6248501427bdb5649e642759c01159554
https://github.com/aguentepe/hbrs-mpl/commit/801e84d09c8bfaf865fece2ffb71b62d8df1a686
https://github.com/aguentepe/hbrs-mpl/commit/7e7f28a84cddb04975bf1f7e5603b8de5a7cf5be
https://github.com/aguentepe/hbrs-mpl/commit/1d932975292de5834b7d8adfa10b6db6b9ca4d0f
https://github.com/aguentepe/hbrs-mpl/commit/b28fe9a2ec6055f47714617176445b05f801a70b
https://github.com/aguentepe/hbrs-mpl/commit/81a31f6e8a94e55038962946b0dc800657f2e557

**Comment by aguentepe** [comment]
Sorry, I didn't know that the PR would be automatically updated with a new push.

**Pull request closed without merging**
